DROP TABLE IF EXISTS artworks;

CREATE TABLE artworks (
    id SERIAL PRIMARY KEY,
    artist_id INTEGER NOT NULL UNIQUE REFERENCES artists(id),
    title VARCHAR(333) NOT NULL,
    img VARCHAR(333) NOT NULL,
    medium VARCHAR(333) NOT NULL,
    format VARCHAR(333) NOT NULL,
    price INTEGER NOT NULL
);
